
module.exports = [
    {short:"  " , name:"Please select a state"},
    {short:"AL" , name:"Alabama"},
    {short:"AK" , name:"Alaska"},
    {short:"AS" , name:"American Samoa"},
    {short:"AZ" , name:"Arizona"},
    {short:"AR" , name:"Arkansas"},
    {short:"CA" , name:"California"},
    {short:"CO" , name:"Colorado"},
    {short:"CT" , name:"Connecticut"},
    {short:"DE" , name:"Delaware"},
    {short:"DC" , name:"District Of Columbia"},
    {short:"FM" , name:"Federated States Of Micronesia"},
    {short:"FL" , name:"Florida"},
    {short:"GA" , name:"Georgia"},
    {short:"GU" , name:"Guam"},
    {short:"HI" , name:"Hawaii"},
    {short:"ID" , name:"Idaho"},
    {short:"IL" , name:"Illinois"},
    {short:"IN" , name:"Indiana"},
    {short:"IA" , name:"Iowa"},
    {short:"KS" , name:"Kansas"},
    {short:"KY" , name:"Kentucky"},
    {short:"LA" , name:"Louisiana"},
    {short:"ME" , name:"Maine"},
    {short:"MH" , name:"Marshall Islands"},
    {short:"MD" , name:"Maryland"},
    {short:"MA" , name:"Massachusetts"},
    {short:"MI" , name:"Michigan"},
    {short:"MN" , name:"Minnesota"},
    {short:"MS" , name:"Mississippi"},
    {short:"MO" , name:"Missouri"},
    {short:"MT" , name:"Montana"},
    {short:"NE" , name:"Nebraska"},
    {short:"NV" , name:"Nevada"},
    {short:"NH" , name:"New Hampshire"},
    {short:"NJ" , name:"New Jersey"},
    {short:"NM" , name:"New Mexico"},
    {short:"NY" , name:"New York"},
    {short:"NC" , name:"North Carolina"},
    {short:"ND" , name:"North Dakota"},
    {short:"MP" , name:"Northern Mariana Islands"},
    {short:"OH" , name:"Ohio"},
    {short:"OK" , name:"Oklahoma"},
    {short:"OR" , name:"Oregon"},
    {short:"PW" , name:"Palau"},
    {short:"PA" , name:"Pennsylvania"},
    {short:"PR" , name:"Puerto Rico"},
    {short:"RI" , name:"Rhode Island"},
    {short:"SC" , name:"South Carolina"},
    {short:"SD" , name:"South Dakota"},
    {short:"TN" , name:"Tennessee"},
    {short:"TX" , name:"Texas"},
    {short:"UT" , name:"Utah"},
    {short:"VT" , name:"Vermont"},
    {short:"VI" , name:"Virgin Islands"},
    {short:"VA" , name:"Virginia"},
    {short:"WA" , name:"Washington"},
    {short:"WV" , name:"West Virginia"},
    {short:"WI" , name:"Wisconsin"},
    {short:"WY" , name:"Wyoming"}
]